CREATE TABLE USERS (
    USER_ID VARCHAR(20) COLLATE utf8mb4_general_ci PRIMARY KEY,
    USERNAME VARCHAR(50) COLLATE utf8mb4_general_ci NOT NULL,
    PASSWORD VARCHAR(255) COLLATE utf8mb4_general_ci NOT NULL,
    LAST_LOGIN DATETIME NULL,
    USER_FLG DECIMAL(1, 0) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
