/* ハードコートデータ */
CREATE TABLE `HDC_DAT` (
    `HDC_ID` int AUTO_INCREMENT PRIMARY KEY,
    `HDC_COAT_DATE` datetime COMMENT 'コート日',
    `HDC_TIMES` decimal(2) COMMENT '回数',
    `HDC_TYPE` varchar(10) COMMENT '種類',
    `HDC_BASE` decimal(2) COMMENT 'ベース',
    `HDC_ADD_PWR` decimal(5,2) COMMENT '加入度数',
    `HDC_LR` varchar(1) COMMENT 'L/R',
    `HDC_COLOR` varchar(5) COMMENT '色',
    `HDC_COAT_CNT` decimal(5) COMMENT 'コート数',
    `HDC_PRE_FOREIGN` decimal(5) COMMENT '硬化前ブツ',
    `HDC_PRE_DROP` decimal(5) COMMENT '硬化前タレ',
    `HDC_PRE_CHIP` decimal(5) COMMENT '硬化前カケ',
    `HDC_PRE_STREAK` decimal(5) COMMENT '硬化前スジ',
    `HDC_PRE_OTHERS` decimal(5) COMMENT '硬化前その他',
    `HDC_TRS_BASE_FAIL` decimal(5) COMMENT '透過基材不良',
    `HDC_TRS_FOREIGN` decimal(5) COMMENT '透過ブツ',
    `HDC_TRS_INCL` decimal(5) COMMENT '透過イブツ',
    `HDC_TRS_SCRATCH` decimal(5) COMMENT '透過キズ',
    `HDC_TRS_COAT_FAIL` decimal(5) COMMENT '透過コート不良',
    `HDC_TRS_DROP` decimal(5) COMMENT '透過タレ',
    `HDC_TRS_STREAK` decimal(5) COMMENT '透過スジ',
    `HDC_TRS_DIRT` decimal(5) COMMENT '透過汚れ',
    `HDC_TRS_CHIP` decimal(5) COMMENT '透過カケ',
    `HDC_PRJ_BASE` decimal(5) COMMENT '投影基材',
    `HDC_PRJ_FOREIGN` decimal(5) COMMENT '投影ブツ',
    `HDC_PRJ_DUST` decimal(5) COMMENT '投影ごみ',
    `HDC_PRJ_SCRATCH` decimal(5) COMMENT '投影キズ',
    `HDC_PRJ_DROP` decimal(5) COMMENT '投影タレ',
    `HDC_PRJ_CHIP` decimal(5) COMMENT '投影カケ',
    `HDC_PRJ_STREAK` decimal(5) COMMENT '投影スジ',
    `HDC_PASS_QTY` decimal(5) COMMENT '合格数'

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ハードコートデータ';