/* スピンコートデータ */
CREATE TABLE `SPC_DAT` (
    `SPC_ID` int AUTO_INCREMENT PRIMARY KEY,
    `SPC_COAT_DATE` datetime COMMENT 'コート日',
    `SPC_INSTR` decimal(3) COMMENT '指図',
    `SPC_BRANCH_NO` varchar(4) COMMENT '枝番',
    `SPC_TYPE` decimal(2) COMMENT '種類',
    `SPC_NAME_1` decimal(3) COMMENT '呼び名1',
    `SPC_NAME_2` varchar(30) COMMENT '呼び名2',
    `SPC_REF_IDX` decimal(4) COMMENT '屈折率',
    `SPC_COAT_COLOR` decimal(3) COMMENT 'コート色',
    `SPC_MACHINE` decimal(2) COMMENT '機',
    `SPC_TIMES` decimal(2) COMMENT '回数',
    `SPC_SHEETS` decimal(5) COMMENT '枚数',
    `SPC_PRE_BLK_DUST` decimal(5) COMMENT '硬化前黒ブツ',
    `SPC_PRE_WHT_DUST` decimal(5) COMMENT '硬化前白ブツ',
    `SPC_PRE_EDGE_FAIL` decimal(5) COMMENT '硬化前外周不良',
    `SPC_PRE_COAT_FAIL` decimal(5) COMMENT '硬化前コート不良',
    `SPC_PRE_DARK_SPOT` decimal(5) COMMENT '硬化前ダークスポット',
    `SPC_PRE_SNAIL` decimal(5) COMMENT '硬化前スネイル',
    `SPC_PRE_MIST` decimal(5) COMMENT '硬化前ミスト',
    `SPC_PRE_WRINKLE` decimal(5) COMMENT '硬化前シワ',
    `SPC_PRE_BRRL_BUB` decimal(5) COMMENT '硬化前バレル泡',
    `SPC_PRE_STICK` decimal(5) COMMENT '硬化前付着物',
    `SPC_PRE_TRBL_FIL` decimal(5) COMMENT '硬化前トラブル不',
    `SPC_PRE_BASE_FIL` decimal(5) COMMENT '硬化前基材不良',
    `SPC_PRE_GOOD_QTY` decimal(5) COMMENT '硬化前良品数',
    `SPC_PRE_NOTE` varchar(40) COMMENT '硬化前備考',
    `SPC_PST_INSP_DATE` datetime COMMENT '硬化後検査日',
    `SPC_PST_SCRATCH` decimal(5) COMMENT '硬化後キズ',
    `SPC_PST_COAT_FIL` decimal(5) COMMENT '硬化後コート不良',
    `SPC_PST_SNAIL` decimal(5) COMMENT '硬化後スネイル',
    `SPC_PST_DARK_SPOT` decimal(5) COMMENT '硬化後ダークスポット',
    `SPC_PST_WRINKLE` decimal(5) COMMENT '硬化後シワ',
    `SPC_PST_BUBBLE` decimal(5) COMMENT '硬化後泡',
    `SPC_PST_EDGE_FAIL` decimal(5) COMMENT '硬化後外周不良',
    `SPC_PST_WHT_DUST` decimal(5) COMMENT '硬化後白ブツ',
    `SPC_PST_BLK_DUST` decimal(5) COMMENT '硬化後黒ブツ',
    `SPC_PST_STICK` decimal(5) COMMENT '硬化後付着物',
    `SPC_PST_PRM_STICK` decimal(5) COMMENT '硬化後プライマー付着跡',
    `SPC_PST_BASE_FAIL` decimal(5) COMMENT '硬化後基材不良',
    `SPC_PST_OTHERS` decimal(5) COMMENT '硬化後その他',
    `SPC_FNL_GD_QTY` decimal(5) COMMENT '最終良品数',

    PRIMARY KEY (`SPC_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='スピンコートデータ';